"""Added uesr pay status 2.0

Revision ID: 0ec46fdb168e
Revises: 3a9f6c16a8f7
Create Date: 2023-05-25 20:37:52.278245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec46fdb168e'
down_revision = '3a9f6c16a8f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pay', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('pay_to', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pay_to')
    op.drop_column('users', 'pay')
    # ### end Alembic commands ###
