"""Added uesr pay status 2.0

Revision ID: 3607a95656e9
Revises: 0ec46fdb168e
Create Date: 2023-05-25 20:40:26.911903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3607a95656e9'
down_revision = '0ec46fdb168e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
